### ISSUE TITLE
找不到GXClientFactory

### ISSUE THREAD

**Issue by dremofly** [gxchain/gxclient-node#4]
![image](https://user-images.githubusercontent.com/21236768/56080789-049ba700-5e38-11e9-9f4d-6471c63044c1.png)

请问这里找不到GXClientFactory的问题该怎么解决

**Comment by lanhaoxiang** [comment]
看起来是eslint报错，不支持import语法，引入babel-env和babel-register解决，通过babel-node运行你的调试程序，或用webpack对代码进行打包

**Comment by lanhaoxiang** [comment]
eslint和babel相关配置可以参考clone下来的gxclient仓库
